In [3]:
#package/lib/mod installation - pip
!pip install pandas numpy seaborn matplotlib scikit-learn

Requirement already satisfied: pandas in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.5.2)
Requirement already satisfied: seaborn in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.11.1)
Requirement already satisfied: scikit-learn in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=9 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in C:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [4]:
import numpy as np   # as means alias

In [5]:
# array
arr1=np.array([1,2,3,4])
print(arr1)
type(arr1)

[1 2 3 4]

numpy.ndarray

In [6]:
#attributes - shape - dimension - dt
arr1.shape

(4,)

In [7]:
arr1.ndim

1

In [9]:
# array operations
arr2=np.array([1,2,3])
arr3=np.array([4,5,6])
add_array = arr2+arr3
mul_array=arr2*arr3
print(add_array)
print(mul_array)

[5 7 9]
[ 4 10 18]

In [11]:
# index and slicing
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [15]:
# finding array elements using indexing 
arr4[1,2]

np.int64(6)

In [16]:
arr4[2,1]

np.int64(8)

In [17]:
arr4[1,] # to get only the first row

array([4, 5, 6])

In [18]:
arr4[1,:]

array([4, 5, 6])

In [20]:
arr4[1,0:1]

array([4])

In [21]:
arr4[1,0:2]

array([4, 5])

In [23]:
arr4[:,1]     # all rows and columns first

array([2, 5, 8])

In [24]:
arr5 = np.arange(12)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [26]:
arr6=arr5.reshape(6,2) # reshape is used to decide the dimension of the array
print(arr6)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

In [27]:
arr6=arr5.reshape(3,4)
print(arr6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [28]:
# statistics
print('Mean:',np.mean(arr5))

Mean: 5.5

In [31]:
print('Median:',np.median(arr5))

Median: 5.5

In [32]:
print('Std dev:',np.std(arr5))

Std dev: 3.452052529534663

In [36]:
# dot product 
a=np.array([[1,2,],[3,4]])
b=np.array([[5,6],[7,8]])
print('Dot Product:',np.dot(a,b))

Dot Product: [[19 22]
 [43 50]]

In [37]:
# Pandas - lib - data maniplulation
import pandas as pd

In [40]:
s=[1,2,7,9]
s1=pd.Series(s)
print(s1)

0    1
1    2
2    7
3    9
dtype: int64

In [41]:
# dictionary
d={
    'Name':"Namratha S",
    'Age':"20",
    'Place':"Mysuru"
}

In [42]:
type(d)

dict

In [58]:
df=pd.DataFrame(d,index = [0])
df

         Name Age   Place
0  Namratha S  20  Mysuru

In [47]:
d1={
    'Name':['Amaira','Shanaya','Chandani','Shrusti'],
    'Year':[2000,1997,2002,2006],
    'Marks':[80,95,79,91]
}

In [49]:
df1=pd.DataFrame(d1)
df1

       Name  Year  Marks
0    Amaira  2000     80
1   Shanaya  1997     95
2  Chandani  2002     79
3   Shrusti  2006     91

In [50]:
df1.Name

0      Amaira
1     Shanaya
2    Chandani
3     Shrusti
Name: Name, dtype: str

In [51]:
df1['Name']

0      Amaira
1     Shanaya
2    Chandani
3     Shrusti
Name: Name, dtype: str

In [52]:
df1['Marks']

0    80
1    95
2    79
3    91
Name: Marks, dtype: int64

In [54]:
df1[['Name','Marks']] # to get columns

       Name  Marks
0    Amaira     80
1   Shanaya     95
2  Chandani     79
3   Shrusti     91

In [59]:
df1.loc[0:2]  # to get rows

       Name  Year  Marks
0    Amaira  2000     80
1   Shanaya  1997     95
2  Chandani  2002     79

In [60]:
# integer location
df1.iloc[1:3,1:2]

   Year
1  1997
2  2002

In [62]:
df1.iloc[3:,2:]

   Marks
3     91

In [63]:
# to get no of rows and columns
df1.shape

(4, 3)

In [64]:
df1.describe()

              Year      Marks
count     4.000000   4.000000
mean   2001.250000  86.250000
std       3.774917   7.973916
min    1997.000000  79.000000
25%    1999.250000  79.750000
50%    2001.000000  85.500000
75%    2003.000000  92.000000
max    2006.000000  95.000000

In [68]:
# to select specific rows
df1.head(2)

      Name  Year  Marks
0   Amaira  2000     80
1  Shanaya  1997     95

In [67]:
df1.tail(2)

       Name  Year  Marks
2  Chandani  2002     79
3   Shrusti  2006     91